name: Flutter Analysis
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  package-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@master
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Check formatting
        run: flutter format --set-exit-if-changed .

      - name: Verify package health
        run: flutter pub publish --dry-run
